### PR TITLE
Added Ninja Grandmaster Hanzo

### PR DESCRIPTION
**Pull request by hah4sk**
Added a 177x254 jpg image for "Ninja Grandmaster Hanzo"
-unsure about filename conventions, I named it "Ninja_Grandmaster_Hanzo.jpg"

### CODE REVIEW

**Comment by AndreOliveiraMendes** [comment]
it is name as [id of card].jpg

**Comment by hah4sk** [comment]
Ok, thanks!  I'll make a new pull request

**Comment by hah4sk** [comment]
Ok cool!  The file should be changed now.  Let me know if that works out.

**Comment by AndreOliveiraMendes** [comment]
@hah4sk you can delet Ninja_Grandmaster_Hanzo.jpg away ~(but that can be done with a pull other pull request later i guess)~

**Comment by hah4sk** [comment]
Sorry I forgot to do that haha.  It should be deleted now.

**Pull request merged**
